version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/treelab
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
